/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as PortalRouteRouteImport } from './routes/portal/route'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as AdminAdAccountsIndexRouteImport } from './routes/admin/ad-accounts/index'
import { Route as AdminAdAccountsAccountIdRouteImport } from './routes/admin/ad-accounts/$accountId'
import { Route as AdminAdjustmentsIndexRouteImport } from './routes/admin/adjustments/index'
import { Route as AdminAuditIndexRouteImport } from './routes/admin/audit/index'
import { Route as AdminClientsIndexRouteImport } from './routes/admin/clients/index'
import { Route as AdminClientsClientIdRouteImport } from './routes/admin/clients/$clientId'
import { Route as AdminLedgerIndexRouteImport } from './routes/admin/ledger/index'
import { Route as AdminLimitRequestsIndexRouteImport } from './routes/admin/limit-requests/index'
import { Route as AdminLimitRequestsRequestIdRouteImport } from './routes/admin/limit-requests/$requestId'
import { Route as AdminPaymentRequestsIndexRouteImport } from './routes/admin/payment-requests/index'
import { Route as AdminPaymentsIndexRouteImport } from './routes/admin/payments/index'
import { Route as AdminPaymentsPaymentIdRouteImport } from './routes/admin/payments/$paymentId'
import { Route as AdminReportsIndexRouteImport } from './routes/admin/reports/index'
import { Route as AdminSearchIndexRouteImport } from './routes/admin/search/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as PortalAdAccountsIndexRouteImport } from './routes/portal/ad-accounts/index'
import { Route as PortalDueIndexRouteImport } from './routes/portal/due/index'
import { Route as PortalLimitRequestsIndexRouteImport } from './routes/portal/limit-requests/index'
import { Route as PortalNotificationsIndexRouteImport } from './routes/portal/notifications/index'
import { Route as PortalPaymentRequestsIndexRouteImport } from './routes/portal/payment-requests/index'
import { Route as PortalProfileIndexRouteImport } from './routes/portal/profile/index'
import { Route as PortalStatementIndexRouteImport } from './routes/portal/statement/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const AdminAdAccountsIndexRoute = AdminAdAccountsIndexRouteImport.update({
  id: '/ad-accounts/',
  path: '/ad-accounts/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdAccountsAccountIdRoute =
  AdminAdAccountsAccountIdRouteImport.update({
    id: '/ad-accounts/$accountId',
    path: '/ad-accounts/$accountId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminAdjustmentsIndexRoute = AdminAdjustmentsIndexRouteImport.update({
  id: '/adjustments/',
  path: '/adjustments/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditIndexRoute = AdminAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClientsIndexRoute = AdminClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClientsClientIdRoute = AdminClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLedgerIndexRoute = AdminLedgerIndexRouteImport.update({
  id: '/ledger/',
  path: '/ledger/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLimitRequestsIndexRoute = AdminLimitRequestsIndexRouteImport.update({
  id: '/limit-requests/',
  path: '/limit-requests/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLimitRequestsRequestIdRoute =
  AdminLimitRequestsRequestIdRouteImport.update({
    id: '/limit-requests/$requestId',
    path: '/limit-requests/$requestId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminPaymentRequestsIndexRoute =
  AdminPaymentRequestsIndexRouteImport.update({
    id: '/payment-requests/',
    path: '/payment-requests/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminPaymentsIndexRoute = AdminPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPaymentsPaymentIdRoute = AdminPaymentsPaymentIdRouteImport.update({
  id: '/payments/$paymentId',
  path: '/payments/$paymentId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsIndexRoute = AdminReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSearchIndexRoute = AdminSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PortalAdAccountsIndexRoute = PortalAdAccountsIndexRouteImport.update({
  id: '/ad-accounts/',
  path: '/ad-accounts/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalDueIndexRoute = PortalDueIndexRouteImport.update({
  id: '/due/',
  path: '/due/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalLimitRequestsIndexRoute =
  PortalLimitRequestsIndexRouteImport.update({
    id: '/limit-requests/',
    path: '/limit-requests/',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalNotificationsIndexRoute =
  PortalNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalPaymentRequestsIndexRoute =
  PortalPaymentRequestsIndexRouteImport.update({
    id: '/payment-requests/',
    path: '/payment-requests/',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalProfileIndexRoute = PortalProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalStatementIndexRoute = PortalStatementIndexRouteImport.update({
  id: '/statement/',
  path: '/statement/',
  getParentRoute: () => PortalRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/ad-accounts/$accountId': typeof AdminAdAccountsAccountIdRoute
  '/admin/clients/$clientId': typeof AdminClientsClientIdRoute
  '/admin/limit-requests/$requestId': typeof AdminLimitRequestsRequestIdRoute
  '/admin/payments/$paymentId': typeof AdminPaymentsPaymentIdRoute
  '/admin/ad-accounts/': typeof AdminAdAccountsIndexRoute
  '/admin/adjustments/': typeof AdminAdjustmentsIndexRoute
  '/admin/audit/': typeof AdminAuditIndexRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/admin/ledger/': typeof AdminLedgerIndexRoute
  '/admin/limit-requests/': typeof AdminLimitRequestsIndexRoute
  '/admin/payment-requests/': typeof AdminPaymentRequestsIndexRoute
  '/admin/payments/': typeof AdminPaymentsIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/admin/search/': typeof AdminSearchIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/portal/ad-accounts/': typeof PortalAdAccountsIndexRoute
  '/portal/due/': typeof PortalDueIndexRoute
  '/portal/limit-requests/': typeof PortalLimitRequestsIndexRoute
  '/portal/notifications/': typeof PortalNotificationsIndexRoute
  '/portal/payment-requests/': typeof PortalPaymentRequestsIndexRoute
  '/portal/profile/': typeof PortalProfileIndexRoute
  '/portal/statement/': typeof PortalStatementIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/admin': typeof AdminIndexRoute
  '/portal': typeof PortalIndexRoute
  '/admin/ad-accounts/$accountId': typeof AdminAdAccountsAccountIdRoute
  '/admin/clients/$clientId': typeof AdminClientsClientIdRoute
  '/admin/limit-requests/$requestId': typeof AdminLimitRequestsRequestIdRoute
  '/admin/payments/$paymentId': typeof AdminPaymentsPaymentIdRoute
  '/admin/ad-accounts': typeof AdminAdAccountsIndexRoute
  '/admin/adjustments': typeof AdminAdjustmentsIndexRoute
  '/admin/audit': typeof AdminAuditIndexRoute
  '/admin/clients': typeof AdminClientsIndexRoute
  '/admin/ledger': typeof AdminLedgerIndexRoute
  '/admin/limit-requests': typeof AdminLimitRequestsIndexRoute
  '/admin/payment-requests': typeof AdminPaymentRequestsIndexRoute
  '/admin/payments': typeof AdminPaymentsIndexRoute
  '/admin/reports': typeof AdminReportsIndexRoute
  '/admin/search': typeof AdminSearchIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/portal/ad-accounts': typeof PortalAdAccountsIndexRoute
  '/portal/due': typeof PortalDueIndexRoute
  '/portal/limit-requests': typeof PortalLimitRequestsIndexRoute
  '/portal/notifications': typeof PortalNotificationsIndexRoute
  '/portal/payment-requests': typeof PortalPaymentRequestsIndexRoute
  '/portal/profile': typeof PortalProfileIndexRoute
  '/portal/statement': typeof PortalStatementIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/ad-accounts/$accountId': typeof AdminAdAccountsAccountIdRoute
  '/admin/clients/$clientId': typeof AdminClientsClientIdRoute
  '/admin/limit-requests/$requestId': typeof AdminLimitRequestsRequestIdRoute
  '/admin/payments/$paymentId': typeof AdminPaymentsPaymentIdRoute
  '/admin/ad-accounts/': typeof AdminAdAccountsIndexRoute
  '/admin/adjustments/': typeof AdminAdjustmentsIndexRoute
  '/admin/audit/': typeof AdminAuditIndexRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/admin/ledger/': typeof AdminLedgerIndexRoute
  '/admin/limit-requests/': typeof AdminLimitRequestsIndexRoute
  '/admin/payment-requests/': typeof AdminPaymentRequestsIndexRoute
  '/admin/payments/': typeof AdminPaymentsIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/admin/search/': typeof AdminSearchIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/portal/ad-accounts/': typeof PortalAdAccountsIndexRoute
  '/portal/due/': typeof PortalDueIndexRoute
  '/portal/limit-requests/': typeof PortalLimitRequestsIndexRoute
  '/portal/notifications/': typeof PortalNotificationsIndexRoute
  '/portal/payment-requests/': typeof PortalPaymentRequestsIndexRoute
  '/portal/profile/': typeof PortalProfileIndexRoute
  '/portal/statement/': typeof PortalStatementIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/portal'
    | '/reset-password'
    | '/forgot-password'
    | '/login'
    | '/admin/'
    | '/portal/'
    | '/admin/ad-accounts/$accountId'
    | '/admin/clients/$clientId'
    | '/admin/limit-requests/$requestId'
    | '/admin/payments/$paymentId'
    | '/admin/ad-accounts/'
    | '/admin/adjustments/'
    | '/admin/audit/'
    | '/admin/clients/'
    | '/admin/ledger/'
    | '/admin/limit-requests/'
    | '/admin/payment-requests/'
    | '/admin/payments/'
    | '/admin/reports/'
    | '/admin/search/'
    | '/admin/settings/'
    | '/admin/users/'
    | '/portal/ad-accounts/'
    | '/portal/due/'
    | '/portal/limit-requests/'
    | '/portal/notifications/'
    | '/portal/payment-requests/'
    | '/portal/profile/'
    | '/portal/statement/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/forgot-password'
    | '/login'
    | '/admin'
    | '/portal'
    | '/admin/ad-accounts/$accountId'
    | '/admin/clients/$clientId'
    | '/admin/limit-requests/$requestId'
    | '/admin/payments/$paymentId'
    | '/admin/ad-accounts'
    | '/admin/adjustments'
    | '/admin/audit'
    | '/admin/clients'
    | '/admin/ledger'
    | '/admin/limit-requests'
    | '/admin/payment-requests'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/search'
    | '/admin/settings'
    | '/admin/users'
    | '/portal/ad-accounts'
    | '/portal/due'
    | '/portal/limit-requests'
    | '/portal/notifications'
    | '/portal/payment-requests'
    | '/portal/profile'
    | '/portal/statement'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/admin'
    | '/portal'
    | '/reset-password'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/admin/'
    | '/portal/'
    | '/admin/ad-accounts/$accountId'
    | '/admin/clients/$clientId'
    | '/admin/limit-requests/$requestId'
    | '/admin/payments/$paymentId'
    | '/admin/ad-accounts/'
    | '/admin/adjustments/'
    | '/admin/audit/'
    | '/admin/clients/'
    | '/admin/ledger/'
    | '/admin/limit-requests/'
    | '/admin/payment-requests/'
    | '/admin/payments/'
    | '/admin/reports/'
    | '/admin/search/'
    | '/admin/settings/'
    | '/admin/users/'
    | '/portal/ad-accounts/'
    | '/portal/due/'
    | '/portal/limit-requests/'
    | '/portal/notifications/'
    | '/portal/payment-requests/'
    | '/portal/profile/'
    | '/portal/statement/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/admin/ad-accounts/': {
      id: '/admin/ad-accounts/'
      path: '/ad-accounts'
      fullPath: '/admin/ad-accounts/'
      preLoaderRoute: typeof AdminAdAccountsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/ad-accounts/$accountId': {
      id: '/admin/ad-accounts/$accountId'
      path: '/ad-accounts/$accountId'
      fullPath: '/admin/ad-accounts/$accountId'
      preLoaderRoute: typeof AdminAdAccountsAccountIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/adjustments/': {
      id: '/admin/adjustments/'
      path: '/adjustments'
      fullPath: '/admin/adjustments/'
      preLoaderRoute: typeof AdminAdjustmentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit/': {
      id: '/admin/audit/'
      path: '/audit'
      fullPath: '/admin/audit/'
      preLoaderRoute: typeof AdminAuditIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/clients/': {
      id: '/admin/clients/'
      path: '/clients'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AdminClientsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/clients/$clientId': {
      id: '/admin/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/admin/clients/$clientId'
      preLoaderRoute: typeof AdminClientsClientIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/ledger/': {
      id: '/admin/ledger/'
      path: '/ledger'
      fullPath: '/admin/ledger/'
      preLoaderRoute: typeof AdminLedgerIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/limit-requests/': {
      id: '/admin/limit-requests/'
      path: '/limit-requests'
      fullPath: '/admin/limit-requests/'
      preLoaderRoute: typeof AdminLimitRequestsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/limit-requests/$requestId': {
      id: '/admin/limit-requests/$requestId'
      path: '/limit-requests/$requestId'
      fullPath: '/admin/limit-requests/$requestId'
      preLoaderRoute: typeof AdminLimitRequestsRequestIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/payment-requests/': {
      id: '/admin/payment-requests/'
      path: '/payment-requests'
      fullPath: '/admin/payment-requests/'
      preLoaderRoute: typeof AdminPaymentRequestsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/payments/': {
      id: '/admin/payments/'
      path: '/payments'
      fullPath: '/admin/payments/'
      preLoaderRoute: typeof AdminPaymentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/payments/$paymentId': {
      id: '/admin/payments/$paymentId'
      path: '/payments/$paymentId'
      fullPath: '/admin/payments/$paymentId'
      preLoaderRoute: typeof AdminPaymentsPaymentIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports/': {
      id: '/admin/reports/'
      path: '/reports'
      fullPath: '/admin/reports/'
      preLoaderRoute: typeof AdminReportsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/search/': {
      id: '/admin/search/'
      path: '/search'
      fullPath: '/admin/search/'
      preLoaderRoute: typeof AdminSearchIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/portal/ad-accounts/': {
      id: '/portal/ad-accounts/'
      path: '/ad-accounts'
      fullPath: '/portal/ad-accounts/'
      preLoaderRoute: typeof PortalAdAccountsIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/due/': {
      id: '/portal/due/'
      path: '/due'
      fullPath: '/portal/due/'
      preLoaderRoute: typeof PortalDueIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/limit-requests/': {
      id: '/portal/limit-requests/'
      path: '/limit-requests'
      fullPath: '/portal/limit-requests/'
      preLoaderRoute: typeof PortalLimitRequestsIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/notifications/': {
      id: '/portal/notifications/'
      path: '/notifications'
      fullPath: '/portal/notifications/'
      preLoaderRoute: typeof PortalNotificationsIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/payment-requests/': {
      id: '/portal/payment-requests/'
      path: '/payment-requests'
      fullPath: '/portal/payment-requests/'
      preLoaderRoute: typeof PortalPaymentRequestsIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/profile/': {
      id: '/portal/profile/'
      path: '/profile'
      fullPath: '/portal/profile/'
      preLoaderRoute: typeof PortalProfileIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/statement/': {
      id: '/portal/statement/'
      path: '/statement'
      fullPath: '/portal/statement/'
      preLoaderRoute: typeof PortalStatementIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAdAccountsAccountIdRoute: typeof AdminAdAccountsAccountIdRoute
  AdminClientsClientIdRoute: typeof AdminClientsClientIdRoute
  AdminLimitRequestsRequestIdRoute: typeof AdminLimitRequestsRequestIdRoute
  AdminPaymentsPaymentIdRoute: typeof AdminPaymentsPaymentIdRoute
  AdminAdAccountsIndexRoute: typeof AdminAdAccountsIndexRoute
  AdminAdjustmentsIndexRoute: typeof AdminAdjustmentsIndexRoute
  AdminAuditIndexRoute: typeof AdminAuditIndexRoute
  AdminClientsIndexRoute: typeof AdminClientsIndexRoute
  AdminLedgerIndexRoute: typeof AdminLedgerIndexRoute
  AdminLimitRequestsIndexRoute: typeof AdminLimitRequestsIndexRoute
  AdminPaymentRequestsIndexRoute: typeof AdminPaymentRequestsIndexRoute
  AdminPaymentsIndexRoute: typeof AdminPaymentsIndexRoute
  AdminReportsIndexRoute: typeof AdminReportsIndexRoute
  AdminSearchIndexRoute: typeof AdminSearchIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminAdAccountsAccountIdRoute: AdminAdAccountsAccountIdRoute,
  AdminClientsClientIdRoute: AdminClientsClientIdRoute,
  AdminLimitRequestsRequestIdRoute: AdminLimitRequestsRequestIdRoute,
  AdminPaymentsPaymentIdRoute: AdminPaymentsPaymentIdRoute,
  AdminAdAccountsIndexRoute: AdminAdAccountsIndexRoute,
  AdminAdjustmentsIndexRoute: AdminAdjustmentsIndexRoute,
  AdminAuditIndexRoute: AdminAuditIndexRoute,
  AdminClientsIndexRoute: AdminClientsIndexRoute,
  AdminLedgerIndexRoute: AdminLedgerIndexRoute,
  AdminLimitRequestsIndexRoute: AdminLimitRequestsIndexRoute,
  AdminPaymentRequestsIndexRoute: AdminPaymentRequestsIndexRoute,
  AdminPaymentsIndexRoute: AdminPaymentsIndexRoute,
  AdminReportsIndexRoute: AdminReportsIndexRoute,
  AdminSearchIndexRoute: AdminSearchIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface PortalRouteRouteChildren {
  PortalIndexRoute: typeof PortalIndexRoute
  PortalAdAccountsIndexRoute: typeof PortalAdAccountsIndexRoute
  PortalDueIndexRoute: typeof PortalDueIndexRoute
  PortalLimitRequestsIndexRoute: typeof PortalLimitRequestsIndexRoute
  PortalNotificationsIndexRoute: typeof PortalNotificationsIndexRoute
  PortalPaymentRequestsIndexRoute: typeof PortalPaymentRequestsIndexRoute
  PortalProfileIndexRoute: typeof PortalProfileIndexRoute
  PortalStatementIndexRoute: typeof PortalStatementIndexRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalIndexRoute: PortalIndexRoute,
  PortalAdAccountsIndexRoute: PortalAdAccountsIndexRoute,
  PortalDueIndexRoute: PortalDueIndexRoute,
  PortalLimitRequestsIndexRoute: PortalLimitRequestsIndexRoute,
  PortalNotificationsIndexRoute: PortalNotificationsIndexRoute,
  PortalPaymentRequestsIndexRoute: PortalPaymentRequestsIndexRoute,
  PortalProfileIndexRoute: PortalProfileIndexRoute,
  PortalStatementIndexRoute: PortalStatementIndexRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
