/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AgencyRouteRouteImport } from './routes/agency/route'
import { Route as ClientRouteRouteImport } from './routes/client/route'
import { Route as PlatformRouteRouteImport } from './routes/platform/route'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SubscriptionSuspendedRouteImport } from './routes/subscription-suspended'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AgencyIndexRouteImport } from './routes/agency/index'
import { Route as ClientIndexRouteImport } from './routes/client/index'
import { Route as PlatformIndexRouteImport } from './routes/platform/index'
import { Route as AgencyAdAccountsIndexRouteImport } from './routes/agency/ad-accounts/index'
import { Route as AgencyAdAccountsAccountIdRouteImport } from './routes/agency/ad-accounts/$accountId'
import { Route as AgencyAdjustmentsIndexRouteImport } from './routes/agency/adjustments/index'
import { Route as AgencyAuditIndexRouteImport } from './routes/agency/audit/index'
import { Route as AgencyClientsIndexRouteImport } from './routes/agency/clients/index'
import { Route as AgencyClientsClientIdRouteImport } from './routes/agency/clients/$clientId'
import { Route as AgencyFinanceIndexRouteImport } from './routes/agency/finance/index'
import { Route as AgencyLedgerIndexRouteImport } from './routes/agency/ledger/index'
import { Route as AgencyLimitRequestsIndexRouteImport } from './routes/agency/limit-requests/index'
import { Route as AgencyLimitRequestsRequestIdRouteImport } from './routes/agency/limit-requests/$requestId'
import { Route as AgencyPaymentRequestsIndexRouteImport } from './routes/agency/payment-requests/index'
import { Route as AgencyPaymentsIndexRouteImport } from './routes/agency/payments/index'
import { Route as AgencyPaymentsPaymentIdRouteImport } from './routes/agency/payments/$paymentId'
import { Route as AgencyReportsIndexRouteImport } from './routes/agency/reports/index'
import { Route as AgencySearchIndexRouteImport } from './routes/agency/search/index'
import { Route as AgencySettingsIndexRouteImport } from './routes/agency/settings/index'
import { Route as AgencyUsersIndexRouteImport } from './routes/agency/users/index'
import { Route as ApiCronMetaSyncRouteImport } from './routes/api/cron/meta-sync'
import { Route as ApiTelegramWebhookRouteImport } from './routes/api/telegram/webhook'
import { Route as ClientAdAccountsIndexRouteImport } from './routes/client/ad-accounts/index'
import { Route as ClientDueIndexRouteImport } from './routes/client/due/index'
import { Route as ClientLimitRequestsIndexRouteImport } from './routes/client/limit-requests/index'
import { Route as ClientNotificationsIndexRouteImport } from './routes/client/notifications/index'
import { Route as ClientPaymentRequestsIndexRouteImport } from './routes/client/payment-requests/index'
import { Route as ClientProfileIndexRouteImport } from './routes/client/profile/index'
import { Route as ClientStatementIndexRouteImport } from './routes/client/statement/index'
import { Route as ClientTeamIndexRouteImport } from './routes/client/team/index'
import { Route as PlatformAccountRequestsIndexRouteImport } from './routes/platform/account-requests/index'
import { Route as PlatformAdAccountsIndexRouteImport } from './routes/platform/ad-accounts/index'
import { Route as PlatformAdAccountsAccountIdRouteImport } from './routes/platform/ad-accounts/$accountId'
import { Route as PlatformLimitRequestsIndexRouteImport } from './routes/platform/limit-requests/index'
import { Route as PlatformLimitRequestsRequestIdRouteImport } from './routes/platform/limit-requests/$requestId'
import { Route as PlatformOrganizationsIndexRouteImport } from './routes/platform/organizations/index'
import { Route as PlatformSettingsIndexRouteImport } from './routes/platform/settings/index'
import { Route as PlatformOrganizationsOrganizationIdIndexRouteImport } from './routes/platform/organizations/$organizationId.index'
import { Route as PlatformOrganizationsOrganizationIdDataRouteImport } from './routes/platform/organizations/$organizationId.data'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyRouteRoute = AgencyRouteRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRouteRoute = ClientRouteRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRouteRoute = PlatformRouteRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionSuspendedRoute = SubscriptionSuspendedRouteImport.update({
  id: '/subscription-suspended',
  path: '/subscription-suspended',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AgencyIndexRoute = AgencyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgencyRouteRoute,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRouteRoute,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const AgencyAdAccountsIndexRoute = AgencyAdAccountsIndexRouteImport.update({
  id: '/ad-accounts/',
  path: '/ad-accounts/',
  getParentRoute: () => AgencyRouteRoute,
} as any)
const AgencyAdAccountsAccountIdRoute =
  AgencyAdAccountsAccountIdRouteImport.update({
    id: '/ad-accounts/$accountId',
    path: '/ad-accounts/$accountId',
    getParentRoute: () => AgencyRouteRoute,
  } as any)
const AgencyAdjustmentsIndexRoute = AgencyAdjustmentsIndexRouteImport.update({
  id: '/adjustments/',
  path: '/adjustments/',
  getParentRoute: () => AgencyRouteRoute,
} as any)
const AgencyAuditIndexRoute = AgencyAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AgencyRouteRoute,
} as any)
const AgencyClientsIndexRoute = AgencyClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AgencyRouteRoute,
} as any)
const AgencyClientsClientIdRoute = AgencyClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => AgencyRouteRoute,
} as any)
const AgencyFinanceIndexRoute = AgencyFinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => AgencyRouteRoute,
} as any)
const AgencyLedgerIndexRoute = AgencyLedgerIndexRouteImport.update({
  id: '/ledger/',
  path: '/ledger/',
  getParentRoute: () => AgencyRouteRoute,
} as any)
const AgencyLimitRequestsIndexRoute =
  AgencyLimitRequestsIndexRouteImport.update({
    id: '/limit-requests/',
    path: '/limit-requests/',
    getParentRoute: () => AgencyRouteRoute,
  } as any)
const AgencyLimitRequestsRequestIdRoute =
  AgencyLimitRequestsRequestIdRouteImport.update({
    id: '/limit-requests/$requestId',
    path: '/limit-requests/$requestId',
    getParentRoute: () => AgencyRouteRoute,
  } as any)
const AgencyPaymentRequestsIndexRoute =
  AgencyPaymentRequestsIndexRouteImport.update({
    id: '/payment-requests/',
    path: '/payment-requests/',
    getParentRoute: () => AgencyRouteRoute,
  } as any)
const AgencyPaymentsIndexRoute = AgencyPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => AgencyRouteRoute,
} as any)
const AgencyPaymentsPaymentIdRoute = AgencyPaymentsPaymentIdRouteImport.update({
  id: '/payments/$paymentId',
  path: '/payments/$paymentId',
  getParentRoute: () => AgencyRouteRoute,
} as any)
const AgencyReportsIndexRoute = AgencyReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AgencyRouteRoute,
} as any)
const AgencySearchIndexRoute = AgencySearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => AgencyRouteRoute,
} as any)
const AgencySettingsIndexRoute = AgencySettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AgencyRouteRoute,
} as any)
const AgencyUsersIndexRoute = AgencyUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AgencyRouteRoute,
} as any)
const ApiCronMetaSyncRoute = ApiCronMetaSyncRouteImport.update({
  id: '/api/cron/meta-sync',
  path: '/api/cron/meta-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramWebhookRoute = ApiTelegramWebhookRouteImport.update({
  id: '/api/telegram/webhook',
  path: '/api/telegram/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientAdAccountsIndexRoute = ClientAdAccountsIndexRouteImport.update({
  id: '/ad-accounts/',
  path: '/ad-accounts/',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientDueIndexRoute = ClientDueIndexRouteImport.update({
  id: '/due/',
  path: '/due/',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientLimitRequestsIndexRoute =
  ClientLimitRequestsIndexRouteImport.update({
    id: '/limit-requests/',
    path: '/limit-requests/',
    getParentRoute: () => ClientRouteRoute,
  } as any)
const ClientNotificationsIndexRoute =
  ClientNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => ClientRouteRoute,
  } as any)
const ClientPaymentRequestsIndexRoute =
  ClientPaymentRequestsIndexRouteImport.update({
    id: '/payment-requests/',
    path: '/payment-requests/',
    getParentRoute: () => ClientRouteRoute,
  } as any)
const ClientProfileIndexRoute = ClientProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientStatementIndexRoute = ClientStatementIndexRouteImport.update({
  id: '/statement/',
  path: '/statement/',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientTeamIndexRoute = ClientTeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => ClientRouteRoute,
} as any)
const PlatformAccountRequestsIndexRoute =
  PlatformAccountRequestsIndexRouteImport.update({
    id: '/account-requests/',
    path: '/account-requests/',
    getParentRoute: () => PlatformRouteRoute,
  } as any)
const PlatformAdAccountsIndexRoute = PlatformAdAccountsIndexRouteImport.update({
  id: '/ad-accounts/',
  path: '/ad-accounts/',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const PlatformAdAccountsAccountIdRoute =
  PlatformAdAccountsAccountIdRouteImport.update({
    id: '/ad-accounts/$accountId',
    path: '/ad-accounts/$accountId',
    getParentRoute: () => PlatformRouteRoute,
  } as any)
const PlatformLimitRequestsIndexRoute =
  PlatformLimitRequestsIndexRouteImport.update({
    id: '/limit-requests/',
    path: '/limit-requests/',
    getParentRoute: () => PlatformRouteRoute,
  } as any)
const PlatformLimitRequestsRequestIdRoute =
  PlatformLimitRequestsRequestIdRouteImport.update({
    id: '/limit-requests/$requestId',
    path: '/limit-requests/$requestId',
    getParentRoute: () => PlatformRouteRoute,
  } as any)
const PlatformOrganizationsIndexRoute =
  PlatformOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => PlatformRouteRoute,
  } as any)
const PlatformSettingsIndexRoute = PlatformSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const PlatformOrganizationsOrganizationIdIndexRoute =
  PlatformOrganizationsOrganizationIdIndexRouteImport.update({
    id: '/organizations/$organizationId/',
    path: '/organizations/$organizationId/',
    getParentRoute: () => PlatformRouteRoute,
  } as any)
const PlatformOrganizationsOrganizationIdDataRoute =
  PlatformOrganizationsOrganizationIdDataRouteImport.update({
    id: '/organizations/$organizationId/data',
    path: '/organizations/$organizationId/data',
    getParentRoute: () => PlatformRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agency': typeof AgencyRouteRouteWithChildren
  '/client': typeof ClientRouteRouteWithChildren
  '/platform': typeof PlatformRouteRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/subscription-suspended': typeof SubscriptionSuspendedRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/agency/': typeof AgencyIndexRoute
  '/client/': typeof ClientIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/agency/ad-accounts/$accountId': typeof AgencyAdAccountsAccountIdRoute
  '/agency/clients/$clientId': typeof AgencyClientsClientIdRoute
  '/agency/limit-requests/$requestId': typeof AgencyLimitRequestsRequestIdRoute
  '/agency/payments/$paymentId': typeof AgencyPaymentsPaymentIdRoute
  '/api/cron/meta-sync': typeof ApiCronMetaSyncRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/platform/ad-accounts/$accountId': typeof PlatformAdAccountsAccountIdRoute
  '/platform/limit-requests/$requestId': typeof PlatformLimitRequestsRequestIdRoute
  '/agency/ad-accounts/': typeof AgencyAdAccountsIndexRoute
  '/agency/adjustments/': typeof AgencyAdjustmentsIndexRoute
  '/agency/audit/': typeof AgencyAuditIndexRoute
  '/agency/clients/': typeof AgencyClientsIndexRoute
  '/agency/finance/': typeof AgencyFinanceIndexRoute
  '/agency/ledger/': typeof AgencyLedgerIndexRoute
  '/agency/limit-requests/': typeof AgencyLimitRequestsIndexRoute
  '/agency/payment-requests/': typeof AgencyPaymentRequestsIndexRoute
  '/agency/payments/': typeof AgencyPaymentsIndexRoute
  '/agency/reports/': typeof AgencyReportsIndexRoute
  '/agency/search/': typeof AgencySearchIndexRoute
  '/agency/settings/': typeof AgencySettingsIndexRoute
  '/agency/users/': typeof AgencyUsersIndexRoute
  '/client/ad-accounts/': typeof ClientAdAccountsIndexRoute
  '/client/due/': typeof ClientDueIndexRoute
  '/client/limit-requests/': typeof ClientLimitRequestsIndexRoute
  '/client/notifications/': typeof ClientNotificationsIndexRoute
  '/client/payment-requests/': typeof ClientPaymentRequestsIndexRoute
  '/client/profile/': typeof ClientProfileIndexRoute
  '/client/statement/': typeof ClientStatementIndexRoute
  '/client/team/': typeof ClientTeamIndexRoute
  '/platform/account-requests/': typeof PlatformAccountRequestsIndexRoute
  '/platform/ad-accounts/': typeof PlatformAdAccountsIndexRoute
  '/platform/limit-requests/': typeof PlatformLimitRequestsIndexRoute
  '/platform/organizations/': typeof PlatformOrganizationsIndexRoute
  '/platform/settings/': typeof PlatformSettingsIndexRoute
  '/platform/organizations/$organizationId/data': typeof PlatformOrganizationsOrganizationIdDataRoute
  '/platform/organizations/$organizationId/': typeof PlatformOrganizationsOrganizationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/subscription-suspended': typeof SubscriptionSuspendedRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/agency': typeof AgencyIndexRoute
  '/client': typeof ClientIndexRoute
  '/platform': typeof PlatformIndexRoute
  '/agency/ad-accounts/$accountId': typeof AgencyAdAccountsAccountIdRoute
  '/agency/clients/$clientId': typeof AgencyClientsClientIdRoute
  '/agency/limit-requests/$requestId': typeof AgencyLimitRequestsRequestIdRoute
  '/agency/payments/$paymentId': typeof AgencyPaymentsPaymentIdRoute
  '/api/cron/meta-sync': typeof ApiCronMetaSyncRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/platform/ad-accounts/$accountId': typeof PlatformAdAccountsAccountIdRoute
  '/platform/limit-requests/$requestId': typeof PlatformLimitRequestsRequestIdRoute
  '/agency/ad-accounts': typeof AgencyAdAccountsIndexRoute
  '/agency/adjustments': typeof AgencyAdjustmentsIndexRoute
  '/agency/audit': typeof AgencyAuditIndexRoute
  '/agency/clients': typeof AgencyClientsIndexRoute
  '/agency/finance': typeof AgencyFinanceIndexRoute
  '/agency/ledger': typeof AgencyLedgerIndexRoute
  '/agency/limit-requests': typeof AgencyLimitRequestsIndexRoute
  '/agency/payment-requests': typeof AgencyPaymentRequestsIndexRoute
  '/agency/payments': typeof AgencyPaymentsIndexRoute
  '/agency/reports': typeof AgencyReportsIndexRoute
  '/agency/search': typeof AgencySearchIndexRoute
  '/agency/settings': typeof AgencySettingsIndexRoute
  '/agency/users': typeof AgencyUsersIndexRoute
  '/client/ad-accounts': typeof ClientAdAccountsIndexRoute
  '/client/due': typeof ClientDueIndexRoute
  '/client/limit-requests': typeof ClientLimitRequestsIndexRoute
  '/client/notifications': typeof ClientNotificationsIndexRoute
  '/client/payment-requests': typeof ClientPaymentRequestsIndexRoute
  '/client/profile': typeof ClientProfileIndexRoute
  '/client/statement': typeof ClientStatementIndexRoute
  '/client/team': typeof ClientTeamIndexRoute
  '/platform/account-requests': typeof PlatformAccountRequestsIndexRoute
  '/platform/ad-accounts': typeof PlatformAdAccountsIndexRoute
  '/platform/limit-requests': typeof PlatformLimitRequestsIndexRoute
  '/platform/organizations': typeof PlatformOrganizationsIndexRoute
  '/platform/settings': typeof PlatformSettingsIndexRoute
  '/platform/organizations/$organizationId/data': typeof PlatformOrganizationsOrganizationIdDataRoute
  '/platform/organizations/$organizationId': typeof PlatformOrganizationsOrganizationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/agency': typeof AgencyRouteRouteWithChildren
  '/client': typeof ClientRouteRouteWithChildren
  '/platform': typeof PlatformRouteRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/subscription-suspended': typeof SubscriptionSuspendedRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/agency/': typeof AgencyIndexRoute
  '/client/': typeof ClientIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/agency/ad-accounts/$accountId': typeof AgencyAdAccountsAccountIdRoute
  '/agency/clients/$clientId': typeof AgencyClientsClientIdRoute
  '/agency/limit-requests/$requestId': typeof AgencyLimitRequestsRequestIdRoute
  '/agency/payments/$paymentId': typeof AgencyPaymentsPaymentIdRoute
  '/api/cron/meta-sync': typeof ApiCronMetaSyncRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/platform/ad-accounts/$accountId': typeof PlatformAdAccountsAccountIdRoute
  '/platform/limit-requests/$requestId': typeof PlatformLimitRequestsRequestIdRoute
  '/agency/ad-accounts/': typeof AgencyAdAccountsIndexRoute
  '/agency/adjustments/': typeof AgencyAdjustmentsIndexRoute
  '/agency/audit/': typeof AgencyAuditIndexRoute
  '/agency/clients/': typeof AgencyClientsIndexRoute
  '/agency/finance/': typeof AgencyFinanceIndexRoute
  '/agency/ledger/': typeof AgencyLedgerIndexRoute
  '/agency/limit-requests/': typeof AgencyLimitRequestsIndexRoute
  '/agency/payment-requests/': typeof AgencyPaymentRequestsIndexRoute
  '/agency/payments/': typeof AgencyPaymentsIndexRoute
  '/agency/reports/': typeof AgencyReportsIndexRoute
  '/agency/search/': typeof AgencySearchIndexRoute
  '/agency/settings/': typeof AgencySettingsIndexRoute
  '/agency/users/': typeof AgencyUsersIndexRoute
  '/client/ad-accounts/': typeof ClientAdAccountsIndexRoute
  '/client/due/': typeof ClientDueIndexRoute
  '/client/limit-requests/': typeof ClientLimitRequestsIndexRoute
  '/client/notifications/': typeof ClientNotificationsIndexRoute
  '/client/payment-requests/': typeof ClientPaymentRequestsIndexRoute
  '/client/profile/': typeof ClientProfileIndexRoute
  '/client/statement/': typeof ClientStatementIndexRoute
  '/client/team/': typeof ClientTeamIndexRoute
  '/platform/account-requests/': typeof PlatformAccountRequestsIndexRoute
  '/platform/ad-accounts/': typeof PlatformAdAccountsIndexRoute
  '/platform/limit-requests/': typeof PlatformLimitRequestsIndexRoute
  '/platform/organizations/': typeof PlatformOrganizationsIndexRoute
  '/platform/settings/': typeof PlatformSettingsIndexRoute
  '/platform/organizations/$organizationId/data': typeof PlatformOrganizationsOrganizationIdDataRoute
  '/platform/organizations/$organizationId/': typeof PlatformOrganizationsOrganizationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agency'
    | '/client'
    | '/platform'
    | '/reset-password'
    | '/subscription-suspended'
    | '/forgot-password'
    | '/login'
    | '/agency/'
    | '/client/'
    | '/platform/'
    | '/agency/ad-accounts/$accountId'
    | '/agency/clients/$clientId'
    | '/agency/limit-requests/$requestId'
    | '/agency/payments/$paymentId'
    | '/api/cron/meta-sync'
    | '/api/telegram/webhook'
    | '/platform/ad-accounts/$accountId'
    | '/platform/limit-requests/$requestId'
    | '/agency/ad-accounts/'
    | '/agency/adjustments/'
    | '/agency/audit/'
    | '/agency/clients/'
    | '/agency/finance/'
    | '/agency/ledger/'
    | '/agency/limit-requests/'
    | '/agency/payment-requests/'
    | '/agency/payments/'
    | '/agency/reports/'
    | '/agency/search/'
    | '/agency/settings/'
    | '/agency/users/'
    | '/client/ad-accounts/'
    | '/client/due/'
    | '/client/limit-requests/'
    | '/client/notifications/'
    | '/client/payment-requests/'
    | '/client/profile/'
    | '/client/statement/'
    | '/client/team/'
    | '/platform/account-requests/'
    | '/platform/ad-accounts/'
    | '/platform/limit-requests/'
    | '/platform/organizations/'
    | '/platform/settings/'
    | '/platform/organizations/$organizationId/data'
    | '/platform/organizations/$organizationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/subscription-suspended'
    | '/forgot-password'
    | '/login'
    | '/agency'
    | '/client'
    | '/platform'
    | '/agency/ad-accounts/$accountId'
    | '/agency/clients/$clientId'
    | '/agency/limit-requests/$requestId'
    | '/agency/payments/$paymentId'
    | '/api/cron/meta-sync'
    | '/api/telegram/webhook'
    | '/platform/ad-accounts/$accountId'
    | '/platform/limit-requests/$requestId'
    | '/agency/ad-accounts'
    | '/agency/adjustments'
    | '/agency/audit'
    | '/agency/clients'
    | '/agency/finance'
    | '/agency/ledger'
    | '/agency/limit-requests'
    | '/agency/payment-requests'
    | '/agency/payments'
    | '/agency/reports'
    | '/agency/search'
    | '/agency/settings'
    | '/agency/users'
    | '/client/ad-accounts'
    | '/client/due'
    | '/client/limit-requests'
    | '/client/notifications'
    | '/client/payment-requests'
    | '/client/profile'
    | '/client/statement'
    | '/client/team'
    | '/platform/account-requests'
    | '/platform/ad-accounts'
    | '/platform/limit-requests'
    | '/platform/organizations'
    | '/platform/settings'
    | '/platform/organizations/$organizationId/data'
    | '/platform/organizations/$organizationId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/agency'
    | '/client'
    | '/platform'
    | '/reset-password'
    | '/subscription-suspended'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/agency/'
    | '/client/'
    | '/platform/'
    | '/agency/ad-accounts/$accountId'
    | '/agency/clients/$clientId'
    | '/agency/limit-requests/$requestId'
    | '/agency/payments/$paymentId'
    | '/api/cron/meta-sync'
    | '/api/telegram/webhook'
    | '/platform/ad-accounts/$accountId'
    | '/platform/limit-requests/$requestId'
    | '/agency/ad-accounts/'
    | '/agency/adjustments/'
    | '/agency/audit/'
    | '/agency/clients/'
    | '/agency/finance/'
    | '/agency/ledger/'
    | '/agency/limit-requests/'
    | '/agency/payment-requests/'
    | '/agency/payments/'
    | '/agency/reports/'
    | '/agency/search/'
    | '/agency/settings/'
    | '/agency/users/'
    | '/client/ad-accounts/'
    | '/client/due/'
    | '/client/limit-requests/'
    | '/client/notifications/'
    | '/client/payment-requests/'
    | '/client/profile/'
    | '/client/statement/'
    | '/client/team/'
    | '/platform/account-requests/'
    | '/platform/ad-accounts/'
    | '/platform/limit-requests/'
    | '/platform/organizations/'
    | '/platform/settings/'
    | '/platform/organizations/$organizationId/data'
    | '/platform/organizations/$organizationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AgencyRouteRoute: typeof AgencyRouteRouteWithChildren
  ClientRouteRoute: typeof ClientRouteRouteWithChildren
  PlatformRouteRoute: typeof PlatformRouteRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SubscriptionSuspendedRoute: typeof SubscriptionSuspendedRoute
  ApiCronMetaSyncRoute: typeof ApiCronMetaSyncRoute
  ApiTelegramWebhookRoute: typeof ApiTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency': {
      id: '/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AgencyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription-suspended': {
      id: '/subscription-suspended'
      path: '/subscription-suspended'
      fullPath: '/subscription-suspended'
      preLoaderRoute: typeof SubscriptionSuspendedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/agency/': {
      id: '/agency/'
      path: '/'
      fullPath: '/agency/'
      preLoaderRoute: typeof AgencyIndexRouteImport
      parentRoute: typeof AgencyRouteRoute
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/platform/': {
      id: '/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/agency/ad-accounts/': {
      id: '/agency/ad-accounts/'
      path: '/ad-accounts'
      fullPath: '/agency/ad-accounts/'
      preLoaderRoute: typeof AgencyAdAccountsIndexRouteImport
      parentRoute: typeof AgencyRouteRoute
    }
    '/agency/ad-accounts/$accountId': {
      id: '/agency/ad-accounts/$accountId'
      path: '/ad-accounts/$accountId'
      fullPath: '/agency/ad-accounts/$accountId'
      preLoaderRoute: typeof AgencyAdAccountsAccountIdRouteImport
      parentRoute: typeof AgencyRouteRoute
    }
    '/agency/adjustments/': {
      id: '/agency/adjustments/'
      path: '/adjustments'
      fullPath: '/agency/adjustments/'
      preLoaderRoute: typeof AgencyAdjustmentsIndexRouteImport
      parentRoute: typeof AgencyRouteRoute
    }
    '/agency/audit/': {
      id: '/agency/audit/'
      path: '/audit'
      fullPath: '/agency/audit/'
      preLoaderRoute: typeof AgencyAuditIndexRouteImport
      parentRoute: typeof AgencyRouteRoute
    }
    '/agency/clients/': {
      id: '/agency/clients/'
      path: '/clients'
      fullPath: '/agency/clients/'
      preLoaderRoute: typeof AgencyClientsIndexRouteImport
      parentRoute: typeof AgencyRouteRoute
    }
    '/agency/clients/$clientId': {
      id: '/agency/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/agency/clients/$clientId'
      preLoaderRoute: typeof AgencyClientsClientIdRouteImport
      parentRoute: typeof AgencyRouteRoute
    }
    '/agency/finance/': {
      id: '/agency/finance/'
      path: '/finance'
      fullPath: '/agency/finance/'
      preLoaderRoute: typeof AgencyFinanceIndexRouteImport
      parentRoute: typeof AgencyRouteRoute
    }
    '/agency/ledger/': {
      id: '/agency/ledger/'
      path: '/ledger'
      fullPath: '/agency/ledger/'
      preLoaderRoute: typeof AgencyLedgerIndexRouteImport
      parentRoute: typeof AgencyRouteRoute
    }
    '/agency/limit-requests/': {
      id: '/agency/limit-requests/'
      path: '/limit-requests'
      fullPath: '/agency/limit-requests/'
      preLoaderRoute: typeof AgencyLimitRequestsIndexRouteImport
      parentRoute: typeof AgencyRouteRoute
    }
    '/agency/limit-requests/$requestId': {
      id: '/agency/limit-requests/$requestId'
      path: '/limit-requests/$requestId'
      fullPath: '/agency/limit-requests/$requestId'
      preLoaderRoute: typeof AgencyLimitRequestsRequestIdRouteImport
      parentRoute: typeof AgencyRouteRoute
    }
    '/agency/payment-requests/': {
      id: '/agency/payment-requests/'
      path: '/payment-requests'
      fullPath: '/agency/payment-requests/'
      preLoaderRoute: typeof AgencyPaymentRequestsIndexRouteImport
      parentRoute: typeof AgencyRouteRoute
    }
    '/agency/payments/': {
      id: '/agency/payments/'
      path: '/payments'
      fullPath: '/agency/payments/'
      preLoaderRoute: typeof AgencyPaymentsIndexRouteImport
      parentRoute: typeof AgencyRouteRoute
    }
    '/agency/payments/$paymentId': {
      id: '/agency/payments/$paymentId'
      path: '/payments/$paymentId'
      fullPath: '/agency/payments/$paymentId'
      preLoaderRoute: typeof AgencyPaymentsPaymentIdRouteImport
      parentRoute: typeof AgencyRouteRoute
    }
    '/agency/reports/': {
      id: '/agency/reports/'
      path: '/reports'
      fullPath: '/agency/reports/'
      preLoaderRoute: typeof AgencyReportsIndexRouteImport
      parentRoute: typeof AgencyRouteRoute
    }
    '/agency/search/': {
      id: '/agency/search/'
      path: '/search'
      fullPath: '/agency/search/'
      preLoaderRoute: typeof AgencySearchIndexRouteImport
      parentRoute: typeof AgencyRouteRoute
    }
    '/agency/settings/': {
      id: '/agency/settings/'
      path: '/settings'
      fullPath: '/agency/settings/'
      preLoaderRoute: typeof AgencySettingsIndexRouteImport
      parentRoute: typeof AgencyRouteRoute
    }
    '/agency/users/': {
      id: '/agency/users/'
      path: '/users'
      fullPath: '/agency/users/'
      preLoaderRoute: typeof AgencyUsersIndexRouteImport
      parentRoute: typeof AgencyRouteRoute
    }
    '/api/cron/meta-sync': {
      id: '/api/cron/meta-sync'
      path: '/api/cron/meta-sync'
      fullPath: '/api/cron/meta-sync'
      preLoaderRoute: typeof ApiCronMetaSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/webhook': {
      id: '/api/telegram/webhook'
      path: '/api/telegram/webhook'
      fullPath: '/api/telegram/webhook'
      preLoaderRoute: typeof ApiTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/ad-accounts/': {
      id: '/client/ad-accounts/'
      path: '/ad-accounts'
      fullPath: '/client/ad-accounts/'
      preLoaderRoute: typeof ClientAdAccountsIndexRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/client/due/': {
      id: '/client/due/'
      path: '/due'
      fullPath: '/client/due/'
      preLoaderRoute: typeof ClientDueIndexRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/client/limit-requests/': {
      id: '/client/limit-requests/'
      path: '/limit-requests'
      fullPath: '/client/limit-requests/'
      preLoaderRoute: typeof ClientLimitRequestsIndexRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/client/notifications/': {
      id: '/client/notifications/'
      path: '/notifications'
      fullPath: '/client/notifications/'
      preLoaderRoute: typeof ClientNotificationsIndexRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/client/payment-requests/': {
      id: '/client/payment-requests/'
      path: '/payment-requests'
      fullPath: '/client/payment-requests/'
      preLoaderRoute: typeof ClientPaymentRequestsIndexRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/client/profile/': {
      id: '/client/profile/'
      path: '/profile'
      fullPath: '/client/profile/'
      preLoaderRoute: typeof ClientProfileIndexRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/client/statement/': {
      id: '/client/statement/'
      path: '/statement'
      fullPath: '/client/statement/'
      preLoaderRoute: typeof ClientStatementIndexRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/client/team/': {
      id: '/client/team/'
      path: '/team'
      fullPath: '/client/team/'
      preLoaderRoute: typeof ClientTeamIndexRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/platform/account-requests/': {
      id: '/platform/account-requests/'
      path: '/account-requests'
      fullPath: '/platform/account-requests/'
      preLoaderRoute: typeof PlatformAccountRequestsIndexRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/platform/ad-accounts/': {
      id: '/platform/ad-accounts/'
      path: '/ad-accounts'
      fullPath: '/platform/ad-accounts/'
      preLoaderRoute: typeof PlatformAdAccountsIndexRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/platform/ad-accounts/$accountId': {
      id: '/platform/ad-accounts/$accountId'
      path: '/ad-accounts/$accountId'
      fullPath: '/platform/ad-accounts/$accountId'
      preLoaderRoute: typeof PlatformAdAccountsAccountIdRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/platform/limit-requests/': {
      id: '/platform/limit-requests/'
      path: '/limit-requests'
      fullPath: '/platform/limit-requests/'
      preLoaderRoute: typeof PlatformLimitRequestsIndexRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/platform/limit-requests/$requestId': {
      id: '/platform/limit-requests/$requestId'
      path: '/limit-requests/$requestId'
      fullPath: '/platform/limit-requests/$requestId'
      preLoaderRoute: typeof PlatformLimitRequestsRequestIdRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/platform/organizations/': {
      id: '/platform/organizations/'
      path: '/organizations'
      fullPath: '/platform/organizations/'
      preLoaderRoute: typeof PlatformOrganizationsIndexRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/platform/settings/': {
      id: '/platform/settings/'
      path: '/settings'
      fullPath: '/platform/settings/'
      preLoaderRoute: typeof PlatformSettingsIndexRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/platform/organizations/$organizationId/': {
      id: '/platform/organizations/$organizationId/'
      path: '/organizations/$organizationId'
      fullPath: '/platform/organizations/$organizationId/'
      preLoaderRoute: typeof PlatformOrganizationsOrganizationIdIndexRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/platform/organizations/$organizationId/data': {
      id: '/platform/organizations/$organizationId/data'
      path: '/organizations/$organizationId/data'
      fullPath: '/platform/organizations/$organizationId/data'
      preLoaderRoute: typeof PlatformOrganizationsOrganizationIdDataRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AgencyRouteRouteChildren {
  AgencyIndexRoute: typeof AgencyIndexRoute
  AgencyAdAccountsAccountIdRoute: typeof AgencyAdAccountsAccountIdRoute
  AgencyClientsClientIdRoute: typeof AgencyClientsClientIdRoute
  AgencyLimitRequestsRequestIdRoute: typeof AgencyLimitRequestsRequestIdRoute
  AgencyPaymentsPaymentIdRoute: typeof AgencyPaymentsPaymentIdRoute
  AgencyAdAccountsIndexRoute: typeof AgencyAdAccountsIndexRoute
  AgencyAdjustmentsIndexRoute: typeof AgencyAdjustmentsIndexRoute
  AgencyAuditIndexRoute: typeof AgencyAuditIndexRoute
  AgencyClientsIndexRoute: typeof AgencyClientsIndexRoute
  AgencyFinanceIndexRoute: typeof AgencyFinanceIndexRoute
  AgencyLedgerIndexRoute: typeof AgencyLedgerIndexRoute
  AgencyLimitRequestsIndexRoute: typeof AgencyLimitRequestsIndexRoute
  AgencyPaymentRequestsIndexRoute: typeof AgencyPaymentRequestsIndexRoute
  AgencyPaymentsIndexRoute: typeof AgencyPaymentsIndexRoute
  AgencyReportsIndexRoute: typeof AgencyReportsIndexRoute
  AgencySearchIndexRoute: typeof AgencySearchIndexRoute
  AgencySettingsIndexRoute: typeof AgencySettingsIndexRoute
  AgencyUsersIndexRoute: typeof AgencyUsersIndexRoute
}

const AgencyRouteRouteChildren: AgencyRouteRouteChildren = {
  AgencyIndexRoute: AgencyIndexRoute,
  AgencyAdAccountsAccountIdRoute: AgencyAdAccountsAccountIdRoute,
  AgencyClientsClientIdRoute: AgencyClientsClientIdRoute,
  AgencyLimitRequestsRequestIdRoute: AgencyLimitRequestsRequestIdRoute,
  AgencyPaymentsPaymentIdRoute: AgencyPaymentsPaymentIdRoute,
  AgencyAdAccountsIndexRoute: AgencyAdAccountsIndexRoute,
  AgencyAdjustmentsIndexRoute: AgencyAdjustmentsIndexRoute,
  AgencyAuditIndexRoute: AgencyAuditIndexRoute,
  AgencyClientsIndexRoute: AgencyClientsIndexRoute,
  AgencyFinanceIndexRoute: AgencyFinanceIndexRoute,
  AgencyLedgerIndexRoute: AgencyLedgerIndexRoute,
  AgencyLimitRequestsIndexRoute: AgencyLimitRequestsIndexRoute,
  AgencyPaymentRequestsIndexRoute: AgencyPaymentRequestsIndexRoute,
  AgencyPaymentsIndexRoute: AgencyPaymentsIndexRoute,
  AgencyReportsIndexRoute: AgencyReportsIndexRoute,
  AgencySearchIndexRoute: AgencySearchIndexRoute,
  AgencySettingsIndexRoute: AgencySettingsIndexRoute,
  AgencyUsersIndexRoute: AgencyUsersIndexRoute,
}

const AgencyRouteRouteWithChildren = AgencyRouteRoute._addFileChildren(
  AgencyRouteRouteChildren,
)

interface ClientRouteRouteChildren {
  ClientIndexRoute: typeof ClientIndexRoute
  ClientAdAccountsIndexRoute: typeof ClientAdAccountsIndexRoute
  ClientDueIndexRoute: typeof ClientDueIndexRoute
  ClientLimitRequestsIndexRoute: typeof ClientLimitRequestsIndexRoute
  ClientNotificationsIndexRoute: typeof ClientNotificationsIndexRoute
  ClientPaymentRequestsIndexRoute: typeof ClientPaymentRequestsIndexRoute
  ClientProfileIndexRoute: typeof ClientProfileIndexRoute
  ClientStatementIndexRoute: typeof ClientStatementIndexRoute
  ClientTeamIndexRoute: typeof ClientTeamIndexRoute
}

const ClientRouteRouteChildren: ClientRouteRouteChildren = {
  ClientIndexRoute: ClientIndexRoute,
  ClientAdAccountsIndexRoute: ClientAdAccountsIndexRoute,
  ClientDueIndexRoute: ClientDueIndexRoute,
  ClientLimitRequestsIndexRoute: ClientLimitRequestsIndexRoute,
  ClientNotificationsIndexRoute: ClientNotificationsIndexRoute,
  ClientPaymentRequestsIndexRoute: ClientPaymentRequestsIndexRoute,
  ClientProfileIndexRoute: ClientProfileIndexRoute,
  ClientStatementIndexRoute: ClientStatementIndexRoute,
  ClientTeamIndexRoute: ClientTeamIndexRoute,
}

const ClientRouteRouteWithChildren = ClientRouteRoute._addFileChildren(
  ClientRouteRouteChildren,
)

interface PlatformRouteRouteChildren {
  PlatformIndexRoute: typeof PlatformIndexRoute
  PlatformAdAccountsAccountIdRoute: typeof PlatformAdAccountsAccountIdRoute
  PlatformLimitRequestsRequestIdRoute: typeof PlatformLimitRequestsRequestIdRoute
  PlatformAccountRequestsIndexRoute: typeof PlatformAccountRequestsIndexRoute
  PlatformAdAccountsIndexRoute: typeof PlatformAdAccountsIndexRoute
  PlatformLimitRequestsIndexRoute: typeof PlatformLimitRequestsIndexRoute
  PlatformOrganizationsIndexRoute: typeof PlatformOrganizationsIndexRoute
  PlatformSettingsIndexRoute: typeof PlatformSettingsIndexRoute
  PlatformOrganizationsOrganizationIdDataRoute: typeof PlatformOrganizationsOrganizationIdDataRoute
  PlatformOrganizationsOrganizationIdIndexRoute: typeof PlatformOrganizationsOrganizationIdIndexRoute
}

const PlatformRouteRouteChildren: PlatformRouteRouteChildren = {
  PlatformIndexRoute: PlatformIndexRoute,
  PlatformAdAccountsAccountIdRoute: PlatformAdAccountsAccountIdRoute,
  PlatformLimitRequestsRequestIdRoute: PlatformLimitRequestsRequestIdRoute,
  PlatformAccountRequestsIndexRoute: PlatformAccountRequestsIndexRoute,
  PlatformAdAccountsIndexRoute: PlatformAdAccountsIndexRoute,
  PlatformLimitRequestsIndexRoute: PlatformLimitRequestsIndexRoute,
  PlatformOrganizationsIndexRoute: PlatformOrganizationsIndexRoute,
  PlatformSettingsIndexRoute: PlatformSettingsIndexRoute,
  PlatformOrganizationsOrganizationIdDataRoute:
    PlatformOrganizationsOrganizationIdDataRoute,
  PlatformOrganizationsOrganizationIdIndexRoute:
    PlatformOrganizationsOrganizationIdIndexRoute,
}

const PlatformRouteRouteWithChildren = PlatformRouteRoute._addFileChildren(
  PlatformRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AgencyRouteRoute: AgencyRouteRouteWithChildren,
  ClientRouteRoute: ClientRouteRouteWithChildren,
  PlatformRouteRoute: PlatformRouteRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SubscriptionSuspendedRoute: SubscriptionSuspendedRoute,
  ApiCronMetaSyncRoute: ApiCronMetaSyncRoute,
  ApiTelegramWebhookRoute: ApiTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
