import { createServerFn } from '@tanstack/react-start'
import { z } from 'zod'
import { getSupabaseAdminClient } from '@/lib/supabase/admin.server'
import { provisionClientLogin } from '@/server/clients/client-login.server'
import { requireAdmin } from '@/server/auth/guards.server'
import { writeAudit } from '@/server/audit/audit.service'
import { bdtToUsd } from '@/server/exchange-rates/rate.service'
import { PERMISSIONS } from '@/lib/permissions/permissions'
import {
  clientCreateSchema,
  clientMembershipStatusSchema,
  clientStatusSchema,
  clientUpdateSchema,
  clientUserCreateSchema,
  clientUserUpdateSchema,
} from '@/schemas/client'
import type { Client } from '@/types/domain'

/** Client list row with active-account count and current due (BDT + USD approx). */
export interface ClientListItem extends Client {
  active_accounts: number
  current_due: string
  current_due_usd: string
}

export const listClientsFn = createServerFn({ method: 'GET' }).handler(
  async (): Promise<Array<ClientListItem>> => {
    const actor = await requireAdmin(PERMISSIONS.CLIENTS_VIEW)
    const admin = getSupabaseAdminClient()

    const { data: clients, error } = await admin
      .from('clients')
      .select('*')
      .eq('organization_id', actor.organizationId)
      .order('created_at', { ascending: false })
    if (error) throw new Error(error.message)

    const { data: activeAssignments } = await admin
      .from('ad_account_assignments')
      .select('client_id')
      .eq('status', 'ACTIVE')
      .eq('organization_id', actor.organizationId)

    const counts = new Map<string, number>()
    for (const row of activeAssignments ?? []) {
      const id = (row as { client_id: string }).client_id
      counts.set(id, (counts.get(id) ?? 0) + 1)
    }

    // Current due per client, ledger-derived (spec §35). Best-effort: if the
    // aggregate isn't available, the list still renders with 0 dues.
    const dueByClient = new Map<string, string>()
    const { data: dueRows } = await admin.rpc('all_client_dues', {
      p_organization_id: actor.organizationId,
    })
    for (const r of (dueRows ?? []) as Array<{
      client_id: string
      current_due: string | number
    }>) {
      dueByClient.set(r.client_id, String(r.current_due))
    }

    return (clients as Array<Client>).map((c) => {
      const dueBdt = dueByClient.get(c.id) ?? '0'
      // Each client carries its own USD rate (spec: per-client billing rate).
      return {
        ...c,
        active_accounts: counts.get(c.id) ?? 0,
        current_due: dueBdt,
        current_due_usd: bdtToUsd(dueBdt, c.usd_rate),
      }
    })
  },
)

export const getClientFn = createServerFn({ method: 'GET' })
  .validator(z.object({ id: z.uuid() }))
  .handler(async ({ data }): Promise<Client> => {
    const actor = await requireAdmin(PERMISSIONS.CLIENTS_VIEW)
    const admin = getSupabaseAdminClient()
    const { data: client, error } = await admin
      .from('clients')
      .select('*')
      .eq('id', data.id)
      .eq('organization_id', actor.organizationId)
      .single()
    if (error) throw new Error(error.message)
    return client as Client
  })

export const createClientFn = createServerFn({ method: 'POST' })
  .validator(clientCreateSchema)
  .handler(async ({ data }): Promise<Client> => {
    const actor = await requireAdmin(PERMISSIONS.CLIENTS_MANAGE)
    const admin = getSupabaseAdminClient()

    // client_code is auto-generated by the DB default (CL-000N).
    const { data: client, error } = await admin
      .from('clients')
      .insert({
        name: data.name,
        company_name: data.company_name ?? null,
        email: data.email ?? null,
        phone: data.phone ?? null,
        address: data.address ?? null,
        usd_rate: data.usd_rate,
        status: data.status,
        segment: data.segment,
        organization_id: actor.organizationId,
      })
      .select('*')
      .single()
    if (error) throw new Error(error.message)

    await writeAudit({
      actorUserId: actor.id,
      organizationId: actor.organizationId,
      action: 'CLIENT_CREATED',
      entityType: 'CLIENT',
      entityId: client.id,
      newValues: client,
    })
    return client as Client
  })

export const updateClientFn = createServerFn({ method: 'POST' })
  .validator(clientUpdateSchema)
  .handler(async ({ data }): Promise<Client> => {
    const actor = await requireAdmin(PERMISSIONS.CLIENTS_MANAGE)
    const admin = getSupabaseAdminClient()

    const { data: before } = await admin
      .from('clients')
      .select('*')
      .eq('id', data.id)
      .eq('organization_id', actor.organizationId)
      .single()
    if (!before) throw new Error('Client not found')

    const { data: client, error } = await admin
      .from('clients')
      .update({
        name: data.name,
        company_name: data.company_name ?? null,
        email: data.email ?? null,
        phone: data.phone ?? null,
        address: data.address ?? null,
        usd_rate: data.usd_rate,
        status: data.status,
        segment: data.segment,
      })
      .eq('id', data.id)
      .eq('organization_id', actor.organizationId)
      .select('*')
      .single()
    if (error) throw new Error(error.message)

    await writeAudit({
      actorUserId: actor.id,
      organizationId: actor.organizationId,
      action: 'CLIENT_UPDATED',
      entityType: 'CLIENT',
      entityId: data.id,
      oldValues: before ?? null,
      newValues: client,
    })
    return client as Client
  })

export const setClientStatusFn = createServerFn({ method: 'POST' })
  .validator(clientStatusSchema)
  .handler(async ({ data }): Promise<Client> => {
    const actor = await requireAdmin(PERMISSIONS.CLIENTS_MANAGE)
    const admin = getSupabaseAdminClient()

    const { data: client, error } = await admin
      .from('clients')
      .update({ status: data.status })
      .eq('id', data.id)
      .eq('organization_id', actor.organizationId)
      .select('*')
      .single()
    if (error) throw new Error(error.message)

    await writeAudit({
      actorUserId: actor.id,
      organizationId: actor.organizationId,
      action: 'CLIENT_STATUS_CHANGED',
      entityType: 'CLIENT',
      entityId: data.id,
      newValues: { status: data.status },
    })
    return client as Client
  })

/**
 * Delete a client — ONLY when it has no financial or account history
 * (spec §7 lists deactivate, not delete; approved financial records are
 * immutable and must never be orphaned). Clients with any ledger entry,
 * payment, payment request, limit request, or account assignment cannot be
 * deleted and must be deactivated instead. Safe to remove a client that was
 * created by mistake and never used.
 */
export const deleteClientFn = createServerFn({ method: 'POST' })
  .validator(z.object({ id: z.uuid() }))
  .handler(async ({ data }): Promise<{ ok: true }> => {
    const actor = await requireAdmin(PERMISSIONS.CLIENTS_MANAGE)
    const admin = getSupabaseAdminClient()

    const { data: client } = await admin
      .from('clients')
      .select('id, client_code, name')
      .eq('id', data.id)
      .eq('organization_id', actor.organizationId)
      .single()
    if (!client) throw new Error('Client not found')

    // Block deletion when any history references this client.
    const historyTables = [
      { table: 'ledger_entries', label: 'ledger entries' },
      { table: 'payments', label: 'payments' },
      { table: 'payment_requests', label: 'payment requests' },
      { table: 'limit_requests', label: 'limit requests' },
      { table: 'ad_account_assignments', label: 'account assignments' },
      { table: 'adjustments', label: 'adjustments' },
    ] as const

    const counts = await Promise.all(
      historyTables.map(({ table }) =>
        admin
          .from(table)
          .select('id', { count: 'exact', head: true })
          .eq('client_id', data.id),
      ),
    )
    const blockers = historyTables
      .map((t, i) => ({ label: t.label, count: counts[i].count ?? 0 }))
      .filter((t) => t.count > 0)
    if (blockers.length > 0) {
      const detail = blockers.map((b) => `${b.count} ${b.label}`).join(', ')
      throw new Error(
        `This client has history (${detail}) and cannot be deleted. Deactivate it instead to preserve the financial record.`,
      )
    }

    // Collect the client's login user ids before the membership rows cascade.
    const { data: memberships } = await admin
      .from('client_memberships')
      .select('user_id')
      .eq('client_id', data.id)
    const loginUserIds = [
      ...new Set(
        ((memberships ?? []) as Array<{ user_id: string }>).map(
          (m) => m.user_id,
        ),
      ),
    ]

    // Delete the client (client_memberships for this client cascade away).
    const { error: delErr } = await admin
      .from('clients')
      .delete()
      .eq('id', data.id)
    if (delErr) throw new Error(delErr.message)

    // Clean up now-orphaned CLIENT logins that belong to no other client.
    for (const userId of loginUserIds) {
      const { count } = await admin
        .from('client_memberships')
        .select('client_id', { count: 'exact', head: true })
        .eq('user_id', userId)
      if ((count ?? 0) === 0) {
        await admin.auth.admin.deleteUser(userId)
      }
    }

    await writeAudit({
      actorUserId: actor.id,
      organizationId: actor.organizationId,
      action: 'CLIENT_DELETED',
      entityType: 'CLIENT',
      entityId: data.id,
      oldValues: client,
    })
    return { ok: true }
  })

export interface ClientUserRow {
  user_id: string
  full_name: string
  email: string
  membership_status: 'ACTIVE' | 'INACTIVE'
}

export const listClientUsersFn = createServerFn({ method: 'GET' })
  .validator(z.object({ client_id: z.uuid() }))
  .handler(async ({ data }): Promise<Array<ClientUserRow>> => {
    const actor = await requireAdmin(PERMISSIONS.CLIENTS_VIEW)
    const admin = getSupabaseAdminClient()

    const { data: memberships, error } = await admin
      .from('client_memberships')
      .select('user_id, status, profile:user_profiles(full_name)')
      .eq('client_id', data.client_id)
      .eq('organization_id', actor.organizationId)
    if (error) throw new Error(error.message)

    const rows = (memberships ?? []) as unknown as Array<{
      user_id: string
      status: 'ACTIVE' | 'INACTIVE'
      profile: { full_name: string } | null
    }>

    // Emails live in auth.users — fetch via the admin API per user.
    const result: Array<ClientUserRow> = []
    for (const m of rows) {
      const { data: userRes } = await admin.auth.admin.getUserById(m.user_id)
      result.push({
        user_id: m.user_id,
        full_name: m.profile?.full_name ?? '',
        email: userRes.user?.email ?? '',
        membership_status: m.status,
      })
    }
    return result
  })

/**
 * Provision a CLIENT login and link it to this client (spec §12, §57). If
 * the email already belongs to a CLIENT-role login for a different client,
 * that existing account is reused (client_memberships is a
 * unique(user_id, client_id) pair, not user_id alone — one login can
 * legitimately belong to several clients) instead of failing with "already
 * registered". See client-login.server.ts.
 */
export const createClientUserFn = createServerFn({ method: 'POST' })
  .validator(clientUserCreateSchema)
  .handler(async ({ data }): Promise<{ user_id: string; reused_existing_user: boolean }> => {
    const actor = await requireAdmin(PERMISSIONS.CLIENTS_MANAGE)
    const admin = getSupabaseAdminClient()

    // Never trust that data.client_id belongs to the caller's own org —
    // provisionClientLogin trusts whatever client_id it's given.
    const { data: client } = await admin
      .from('clients')
      .select('id')
      .eq('id', data.client_id)
      .eq('organization_id', actor.organizationId)
      .maybeSingle()
    if (!client) throw new Error('Client not found')

    const { user_id: userId, reused_existing_user } = await provisionClientLogin({
      email: data.email,
      full_name: data.full_name,
      password: data.password,
      client_id: data.client_id,
      organization_id: actor.organizationId,
    })

    await writeAudit({
      actorUserId: actor.id,
      organizationId: actor.organizationId,
      action: 'CLIENT_USER_CREATED',
      entityType: 'CLIENT',
      entityId: data.client_id,
      newValues: { user_id: userId, email: data.email, reused_existing_user },
    })
    return { user_id: userId, reused_existing_user }
  })

/** Edit a client login's name/email (admin, from the client detail page's
 * Logins tab). Password reset is a separate, not-yet-built concern. */
export const updateClientUserProfileFn = createServerFn({ method: 'POST' })
  .validator(clientUserUpdateSchema)
  .handler(async ({ data }): Promise<{ ok: true }> => {
    const actor = await requireAdmin(PERMISSIONS.CLIENTS_MANAGE)
    const admin = getSupabaseAdminClient()

    // Scope check: the target user must actually be a member of this client
    // — never trust the client_id/user_id pairing without verifying it.
    const { data: membership } = await admin
      .from('client_memberships')
      .select('user_id')
      .eq('user_id', data.user_id)
      .eq('client_id', data.client_id)
      .eq('organization_id', actor.organizationId)
      .maybeSingle()
    if (!membership) {
      throw new Error('That login is not a member of this client')
    }

    const { error: profileErr } = await admin
      .from('user_profiles')
      .update({ full_name: data.full_name })
      .eq('user_id', data.user_id)
      .eq('organization_id', actor.organizationId)
    if (profileErr) throw new Error(profileErr.message)

    const { error: authErr } = await admin.auth.admin.updateUserById(
      data.user_id,
      { email: data.email, email_confirm: true },
    )
    if (authErr) throw new Error(authErr.message)

    await writeAudit({
      actorUserId: actor.id,
      organizationId: actor.organizationId,
      action: 'CLIENT_USER_UPDATED',
      entityType: 'CLIENT',
      entityId: data.client_id,
      newValues: { user_id: data.user_id, full_name: data.full_name, email: data.email },
    })
    return { ok: true }
  })

/** Activate/deactivate a client login's membership (admin, from the Logins
 * tab) — the fix for spec's "no active client access" lockout screen,
 * previously only fixable by editing the database directly. */
export const setClientMembershipStatusFn = createServerFn({ method: 'POST' })
  .validator(clientMembershipStatusSchema)
  .handler(async ({ data }): Promise<{ ok: true }> => {
    const actor = await requireAdmin(PERMISSIONS.CLIENTS_MANAGE)
    const admin = getSupabaseAdminClient()

    const { data: updated, error } = await admin
      .from('client_memberships')
      .update({ status: data.status })
      .eq('user_id', data.user_id)
      .eq('client_id', data.client_id)
      .eq('organization_id', actor.organizationId)
      .select('user_id')
      .maybeSingle()
    if (error) throw new Error(error.message)
    if (!updated) {
      throw new Error('That login is not a member of this client')
    }

    await writeAudit({
      actorUserId: actor.id,
      organizationId: actor.organizationId,
      action: 'CLIENT_MEMBERSHIP_STATUS_CHANGED',
      entityType: 'CLIENT',
      entityId: data.client_id,
      newValues: { user_id: data.user_id, status: data.status },
    })
    return { ok: true }
  })
