import { createServerFn } from '@tanstack/react-start'
import { z } from 'zod'
import { getSupabaseAdminClient } from '@/lib/supabase/admin.server'
import { requireAdmin } from '@/server/auth/guards.server'
import { writeAudit } from '@/server/audit/audit.service'
import { bdtToUsd, currentUsdRate } from '@/server/exchange-rates/rate.service'
import { PERMISSIONS } from '@/lib/permissions/permissions'
import {
  clientCreateSchema,
  clientStatusSchema,
  clientUpdateSchema,
  clientUserCreateSchema,
} from '@/schemas/client'
import type { Client } from '@/types/domain'

/** Client list row with active-account count and current due (BDT + USD approx). */
export interface ClientListItem extends Client {
  active_accounts: number
  current_due: string
  current_due_usd: string
}

export const listClientsFn = createServerFn({ method: 'GET' }).handler(
  async (): Promise<Array<ClientListItem>> => {
    await requireAdmin(PERMISSIONS.CLIENTS_VIEW)
    const admin = getSupabaseAdminClient()

    const { data: clients, error } = await admin
      .from('clients')
      .select('*')
      .order('created_at', { ascending: false })
    if (error) throw new Error(error.message)

    const { data: activeAssignments } = await admin
      .from('ad_account_assignments')
      .select('client_id')
      .eq('status', 'ACTIVE')

    const counts = new Map<string, number>()
    for (const row of activeAssignments ?? []) {
      const id = (row as { client_id: string }).client_id
      counts.set(id, (counts.get(id) ?? 0) + 1)
    }

    // Current due per client, ledger-derived (spec §35). Best-effort: if the
    // aggregate isn't available, the list still renders with 0 dues.
    const dueByClient = new Map<string, string>()
    const { data: dueRows } = await admin.rpc('all_client_dues')
    for (const r of (dueRows ?? []) as Array<{
      client_id: string
      current_due: string | number
    }>) {
      dueByClient.set(r.client_id, String(r.current_due))
    }

    const rate = await currentUsdRate()

    return (clients as Array<Client>).map((c) => {
      const dueBdt = dueByClient.get(c.id) ?? '0'
      return {
        ...c,
        active_accounts: counts.get(c.id) ?? 0,
        current_due: dueBdt,
        current_due_usd: bdtToUsd(dueBdt, rate),
      }
    })
  },
)

export const getClientFn = createServerFn({ method: 'GET' })
  .validator(z.object({ id: z.uuid() }))
  .handler(async ({ data }): Promise<Client> => {
    await requireAdmin(PERMISSIONS.CLIENTS_VIEW)
    const admin = getSupabaseAdminClient()
    const { data: client, error } = await admin
      .from('clients')
      .select('*')
      .eq('id', data.id)
      .single()
    if (error) throw new Error(error.message)
    return client as Client
  })

export const createClientFn = createServerFn({ method: 'POST' })
  .validator(clientCreateSchema)
  .handler(async ({ data }): Promise<Client> => {
    const actor = await requireAdmin(PERMISSIONS.CLIENTS_MANAGE)
    const admin = getSupabaseAdminClient()

    // client_code is auto-generated by the DB default (CL-000N).
    const { data: client, error } = await admin
      .from('clients')
      .insert({
        name: data.name,
        company_name: data.company_name ?? null,
        email: data.email ?? null,
        phone: data.phone ?? null,
        address: data.address ?? null,
        status: data.status,
      })
      .select('*')
      .single()
    if (error) throw new Error(error.message)

    await writeAudit({
      actorUserId: actor.id,
      action: 'CLIENT_CREATED',
      entityType: 'CLIENT',
      entityId: client.id,
      newValues: client,
    })
    return client as Client
  })

export const updateClientFn = createServerFn({ method: 'POST' })
  .validator(clientUpdateSchema)
  .handler(async ({ data }): Promise<Client> => {
    const actor = await requireAdmin(PERMISSIONS.CLIENTS_MANAGE)
    const admin = getSupabaseAdminClient()

    const { data: before } = await admin
      .from('clients')
      .select('*')
      .eq('id', data.id)
      .single()

    const { data: client, error } = await admin
      .from('clients')
      .update({
        name: data.name,
        company_name: data.company_name ?? null,
        email: data.email ?? null,
        phone: data.phone ?? null,
        address: data.address ?? null,
        status: data.status,
      })
      .eq('id', data.id)
      .select('*')
      .single()
    if (error) throw new Error(error.message)

    await writeAudit({
      actorUserId: actor.id,
      action: 'CLIENT_UPDATED',
      entityType: 'CLIENT',
      entityId: data.id,
      oldValues: before ?? null,
      newValues: client,
    })
    return client as Client
  })

export const setClientStatusFn = createServerFn({ method: 'POST' })
  .validator(clientStatusSchema)
  .handler(async ({ data }): Promise<Client> => {
    const actor = await requireAdmin(PERMISSIONS.CLIENTS_MANAGE)
    const admin = getSupabaseAdminClient()

    const { data: client, error } = await admin
      .from('clients')
      .update({ status: data.status })
      .eq('id', data.id)
      .select('*')
      .single()
    if (error) throw new Error(error.message)

    await writeAudit({
      actorUserId: actor.id,
      action: 'CLIENT_STATUS_CHANGED',
      entityType: 'CLIENT',
      entityId: data.id,
      newValues: { status: data.status },
    })
    return client as Client
  })

/**
 * Delete a client — ONLY when it has no financial or account history
 * (spec §7 lists deactivate, not delete; approved financial records are
 * immutable and must never be orphaned). Clients with any ledger entry,
 * payment, payment request, limit request, or account assignment cannot be
 * deleted and must be deactivated instead. Safe to remove a client that was
 * created by mistake and never used.
 */
export const deleteClientFn = createServerFn({ method: 'POST' })
  .validator(z.object({ id: z.uuid() }))
  .handler(async ({ data }): Promise<{ ok: true }> => {
    const actor = await requireAdmin(PERMISSIONS.CLIENTS_MANAGE)
    const admin = getSupabaseAdminClient()

    const { data: client } = await admin
      .from('clients')
      .select('id, client_code, name')
      .eq('id', data.id)
      .single()
    if (!client) throw new Error('Client not found')

    // Block deletion when any history references this client.
    const historyTables = [
      { table: 'ledger_entries', label: 'ledger entries' },
      { table: 'payments', label: 'payments' },
      { table: 'payment_requests', label: 'payment requests' },
      { table: 'limit_requests', label: 'limit requests' },
      { table: 'ad_account_assignments', label: 'account assignments' },
      { table: 'adjustments', label: 'adjustments' },
    ] as const

    const counts = await Promise.all(
      historyTables.map(({ table }) =>
        admin
          .from(table)
          .select('id', { count: 'exact', head: true })
          .eq('client_id', data.id),
      ),
    )
    const blockers = historyTables
      .map((t, i) => ({ label: t.label, count: counts[i].count ?? 0 }))
      .filter((t) => t.count > 0)
    if (blockers.length > 0) {
      const detail = blockers.map((b) => `${b.count} ${b.label}`).join(', ')
      throw new Error(
        `This client has history (${detail}) and cannot be deleted. Deactivate it instead to preserve the financial record.`,
      )
    }

    // Collect the client's login user ids before the membership rows cascade.
    const { data: memberships } = await admin
      .from('client_memberships')
      .select('user_id')
      .eq('client_id', data.id)
    const loginUserIds = [
      ...new Set(
        ((memberships ?? []) as Array<{ user_id: string }>).map(
          (m) => m.user_id,
        ),
      ),
    ]

    // Delete the client (client_memberships for this client cascade away).
    const { error: delErr } = await admin
      .from('clients')
      .delete()
      .eq('id', data.id)
    if (delErr) throw new Error(delErr.message)

    // Clean up now-orphaned CLIENT logins that belong to no other client.
    for (const userId of loginUserIds) {
      const { count } = await admin
        .from('client_memberships')
        .select('client_id', { count: 'exact', head: true })
        .eq('user_id', userId)
      if ((count ?? 0) === 0) {
        await admin.auth.admin.deleteUser(userId)
      }
    }

    await writeAudit({
      actorUserId: actor.id,
      action: 'CLIENT_DELETED',
      entityType: 'CLIENT',
      entityId: data.id,
      oldValues: client,
    })
    return { ok: true }
  })

export interface ClientUserRow {
  user_id: string
  full_name: string
  email: string
  membership_status: 'ACTIVE' | 'INACTIVE'
}

export const listClientUsersFn = createServerFn({ method: 'GET' })
  .validator(z.object({ client_id: z.uuid() }))
  .handler(async ({ data }): Promise<Array<ClientUserRow>> => {
    await requireAdmin(PERMISSIONS.CLIENTS_VIEW)
    const admin = getSupabaseAdminClient()

    const { data: memberships, error } = await admin
      .from('client_memberships')
      .select('user_id, status, profile:user_profiles(full_name)')
      .eq('client_id', data.client_id)
    if (error) throw new Error(error.message)

    const rows = (memberships ?? []) as unknown as Array<{
      user_id: string
      status: 'ACTIVE' | 'INACTIVE'
      profile: { full_name: string } | null
    }>

    // Emails live in auth.users — fetch via the admin API per user.
    const result: Array<ClientUserRow> = []
    for (const m of rows) {
      const { data: userRes } = await admin.auth.admin.getUserById(m.user_id)
      result.push({
        user_id: m.user_id,
        full_name: m.profile?.full_name ?? '',
        email: userRes.user?.email ?? '',
        membership_status: m.status,
      })
    }
    return result
  })

/**
 * Provision a new CLIENT login and link it to this client (spec §12, §57).
 * The login is created with app_role=CLIENT in app_metadata (server-only),
 * email pre-confirmed, and an ACTIVE membership row.
 */
export const createClientUserFn = createServerFn({ method: 'POST' })
  .validator(clientUserCreateSchema)
  .handler(async ({ data }): Promise<{ user_id: string }> => {
    const actor = await requireAdmin(PERMISSIONS.CLIENTS_MANAGE)
    const admin = getSupabaseAdminClient()

    const { data: created, error } = await admin.auth.admin.createUser({
      email: data.email,
      password: data.password,
      email_confirm: true,
      app_metadata: { app_role: 'CLIENT' },
      user_metadata: { full_name: data.full_name },
    })
    if (error) throw new Error(error.message)
    const userId = created.user.id

    // The on_auth_user_created trigger creates the profile; ensure the name.
    await admin
      .from('user_profiles')
      .update({ full_name: data.full_name })
      .eq('user_id', userId)

    const { error: memErr } = await admin
      .from('client_memberships')
      .insert({ user_id: userId, client_id: data.client_id, status: 'ACTIVE' })
    if (memErr) throw new Error(memErr.message)

    await writeAudit({
      actorUserId: actor.id,
      action: 'CLIENT_USER_CREATED',
      entityType: 'CLIENT',
      entityId: data.client_id,
      newValues: { user_id: userId, email: data.email },
    })
    return { user_id: userId }
  })
